name: flutter_ddd_skeleton_monorepo
description: Flutter demo app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_ddd_skeleton_monorepo_data:
    path: packages/flutter_ddd_skeleton_monorepo_data
  flutter_ddd_skeleton_monorepo_domain:
    path: packages/flutter_ddd_skeleton_monorepo_domain
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.2.2
  hydrated_bloc: ^9.1.3
  injectable: ^2.3.2
  intl: ^0.19.0
  lottie: ^3.0.0
  path_provider: ^2.1.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  melos: ^6.0.0
  mocktail: ^1.0.0
  rename_app: ^1.3.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/app/assets
  integrations:
    flutter_svg: true
    lottie: true
